pipeline {
	agent any
	environment {
    	DOCKERHUB_CREDENTIALS = credentials('dockerhub')
  	}
	stages {
		stage("Lint HTML") {
			steps {
				sh 'tidy -q -e *.html'
			}
		}

		stage("Change Permissions") {
			steps {
				sh '''
					cd ./blue-app
					chmod +x ./build-image.sh
					chmod +x ./remove-image.sh
				'''
				sh '''
					cd ./green-app
					chmod +x ./build-image.sh
					chmod +x ./remove-image.sh
				'''
			}
		}

		stage("Build Docker Images") {
			parallel {
				stage("Build Blue Image") {
					steps {
						sh 'echo " ---- Building and push to dockerhub Blue Image --- "'
						sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
						sh '''
							echo $BUILD_ID
							cd ./blue-app
							./build-image.sh
						'''					
					}
				}
				stage("Build Green Image") {
					steps {	
						sh 'echo " ---- Building and push to dockerhub Green Image --- "'
						sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
						sh '''
							echo $BUILD_ID
							cd ./green-app
							./build-image.sh
						'''
					}
				}
			}
		}
		
		stage ("Remove Docker Images") {
			parallel {
				stage("Remove Blue Image") {
					steps {
						sh 'echo " ---- Removing Blue Image --- "'
						sh './blue-app/remove-image.sh'
					}
				}
				stage("Remove Green Image") {
					steps {
						sh 'echo " ---- Removing Green Image --- "'
						sh 'cd ./green-app/remove-image.sh'
					}
				}
			}
		}

		stage('Create Kubernetes Cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws_credentials') {
					sh 'eksctl create cluster --name uda-cluster --version 1.27 --region us-east-1 --nodegroup-name uda-worker --node-type t3.micro --nodes 2 --nodes-min 1 --nodes-max 3 --managed'
				}
			}
		}

		stage('Configure kubectl') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws_credentials') {
					sh 'aws eks --region us-east-1 update-kubeconfig --name uda-cluster'
				}
			}
		}

		stage("Deploy Application Containers") {
			parallel {
				stage("Deploy Blue Application Container") {
					steps {
						withAWS(region:'us-east-1',credentials:'aws_credentials') {
							sh 'kubectl apply -f kubernetes/blue-controller.yaml'
						}
					}
				}
				stage("Deploy Green Application Container") {
					steps {
						withAWS(region:'us-east-1',credentials:'aws_credentials') {
							sh 'kubectl apply -f kubernetes/green-controller.yaml'
						}
					}
				}
			}
		}

		stage("Run Blue Application") {
			steps {
				withAWS(region:'us-east-1',credentials:'aws_credentials') {
					sh 'kubectl apply -f kubernetes/blue-service.yaml'
				}
			}
		}

		stage("Blue Application") {
			steps {
				withAWS(region:'us-east-1',credentials:'aws_credentials') {
					sleep time: 1, unit: 'MINUTES'
					sh 'kubectl get nodes,deploy,svc,pod'
					sh 'kubectl get service -o wide'
					sleep time: 1, unit: 'MINUTES'
				}
			}
		}

		stage("Switch to Green Application") {
			steps {
				withAWS(region:'us-east-1',credentials:'aws_credentials') {
					sh 'kubectl apply -f green-app/green-service.yaml'
				}
			}
		}

		stage("Green Application") {
			steps {
				withAWS(region:'us-east-1',credentials:'aws_credentials') {
					sleep time: 1, unit: 'MINUTES'
					sh 'kubectl get nodes,deploy,svc,pod'
					sh 'kubectl get service -o wide'
				}
			}
		}
	}
}