pipeline {
	agent any
	stages {

		stage('Create Kubernetes Cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws_credentials') {
					sh 'eksctl create cluster --name uda-cluster --version 1.26 --region us-east-1 --nodegroup-name uda-worker --node-type t3.micro --nodes 4 --nodes-min 2 --nodes-max 4 --managed'
				}
			}
		}

		stage('Configure kubectl') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws_credentials') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name udacluster
					'''
				}
			}
		}

	}
}