kind: Service
apiVersion: v1
metadata:
    name: servicelb
    labels:
        app: servicelb
spec:
    ports:
        - port: 8000
          targetPort: 80
    selector:
        app: blue
    type: LoadBalancer