kind: Service
apiVersion: v1
metadata:
    name: servicebluelb
    labels:
        app: servicebluelb
spec:
    ports:
        - port: 8000
          targetPort: 80
    selector:
        app: blue
        version: v1.0.0
    type: LoadBalancer