kind: ReplicationController
apiVersion: v1
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      labels:
        app: green
        version: v2.0.0
    spec:
      containers:
      - name: green
        image: johnwick98/uda-capstone-green-app
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: v2.0.0