kind: Service
apiVersion: v1
metadata:
    name: servicegreenlb
    labels:
        app: servicegreenlb
spec:
    ports:
        - port: 8000
          targetPort: 80
    selector:
        app: green
        version: v2.0.0
    type: LoadBalancer